import type { Memo } from "@/lib/memo-types"

export const sampleMemos: Memo[] = [
  {
    id: "1",
    title: "오늘의 할 일",
    content: "장보기: 우유, 달걀, 빵, 과일\n운동 30분\n독서 1시간\n프로젝트 마무리",
    color: "yellow",
    category: "할 일",
    pinned: true,
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 1800000),
  },
  {
    id: "2",
    title: "프로젝트 아이디어",
    content: "사용자 경험을 개선하기 위한 새로운 UI 디자인 컨셉. 밝고 따뜻한 컬러 팔레트를 활용하여 편안한 느낌을 주는 인터페이스를 설계하자.",
    color: "peach",
    category: "아이디어",
    pinned: true,
    createdAt: new Date(Date.now() - 86400000),
    updatedAt: new Date(Date.now() - 7200000),
  },
  {
    id: "3",
    title: "독서 노트 - 아토믹 해빗",
    content: "습관을 바꾸는 가장 효과적인 방법은 정체성을 바꾸는 것이다. 결과 중심이 아닌 정체성 중심의 습관 변화가 중요하다.",
    color: "mint",
    category: "독서",
    pinned: false,
    createdAt: new Date(Date.now() - 172800000),
    updatedAt: new Date(Date.now() - 86400000),
  },
  {
    id: "4",
    title: "회의 메모",
    content: "다음 주 월요일 오전 10시 팀 미팅\n주간 보고서 준비 필요\n새로운 기능 출시 일정 확인",
    color: "sky",
    category: "업무",
    pinned: false,
    createdAt: new Date(Date.now() - 259200000),
    updatedAt: new Date(Date.now() - 172800000),
  },
  {
    id: "5",
    title: "주말 계획",
    content: "토요일: 카페에서 독서\n일요일: 요리 도전 - 파스타 만들기\n영화 보기",
    color: "lavender",
    category: "일상",
    pinned: false,
    createdAt: new Date(Date.now() - 345600000),
    updatedAt: new Date(Date.now() - 259200000),
  },
  {
    id: "6",
    title: "새로운 레시피",
    content: "크림 파스타: 올리브 오일, 마늘, 베이컨, 생크림, 파마산 치즈, 파슬리. 면은 알덴테로 삶을 것!",
    color: "yellow",
    category: "일상",
    pinned: false,
    createdAt: new Date(Date.now() - 432000000),
    updatedAt: new Date(Date.now() - 345600000),
  },
]
